#ChaosEssentials Config
#Database Information
tableprefix: 'ce_'
jdbc: 'jdbc:mysql://localhost/'
database: 'chaosessentials'
username: 'root'
password: ''

Inv_name: '&8» &6Verfügbare Befehle'

Inv_size: 4

targetWarp: 'lobby'

#############################################
###### Purchaseable Commands Messages #######
#############################################

nograntedpermission: '&8[&e&l!&8] &c&lServer &8» &cDer Spieler &e%target% &chat keinen
  granted /%command% Befehl'

commandnotavailable: '&8[&e&l!&8] &c&lServer &8» &cDer Befehl &e/%command% &cist nicht
  verfügbar'

buyconfirmation: '&8[&e&l!&8] &c&lServer &8» &aDu hast erfolgreich den Befehl &e/%command%
  &afür &6%duration% Tage/Nutzungen &agekauft'

notenoughmoney: '&8[&e&l!&8] &c&lServer &8» &cDu brauchst &e%price% &cfür diesen Befehl'

nopermission: '&8[&e&l!&8] &c&lServer &8» &cDazu hast du keine Rechte'

oncooldown: '&8[&e&l!&8] &c&lServer &8» &7Der Befehl &e/%command% &7 besitzt aktuell
  noch einen Cooldown von &e%time%'

oncooldown_self: '&8[&e&l!&8] &c&lServer &8» &7Der Spieler &e%target% &7hat auf diesen
  Befehl noch einen Cooldown'

giftconfirmation_self: '&8[&e&l!&8] &c&lServer &8» &7Du hast den Befehl &e/%command%
  &7für den Spieler &6%target% &7erfolgreich gekauft'

giftconfirmation_receiver: '&8[&e&l!&8] &c&lServer &8» &7Der Spieler &e%player% &7hat
  dir den Befehl &e/%command% &7für &6%duration% &7Tage/Benutzungen &7gekauft'

grantconfirmation_self: '&8[&e&l!&8] &c&lServer &8» &aDu hast &e%target% &aden Befehl
  &e/%command% &afür &6%duration% &aTage/Nutzungen gegeben'

grantconfirmation_receiver: '&8[&e&l!&8] &c&lServer &8» &e%player% &7hat dir den Befehl
  &e/%command% &7für &6%duration% Tage/Nutzungen &7gegeben'

ungrantconfirmation: '&8[&e&l!&8] &c&lServer &8» &cDu hast von &e%target% &cden Befehl
  &e/%command% &cwieder entfernt'

playernotfound: '&8[&e&l!&8] &c&lServer &8» &cDieser Spieler ist nicht online'

TargetIsSender: '&8[&e&l!&8] &c&lServer &8» &cDu kannst diesen Befehl nicht bei dir
  selbst ausführen'

has_perm_already: '&8[&e&l!&8] &c&lServer &8» &cDu hast diesen Befehl bereits!'

target_has_perm_already: '&8[&e&l!&8] &c&lServer &8» &cDieser Spieler hat diesen Befehl bereits!'

last_use: '&8[&e&l!&8] &c&lServer &8» &cBefehl wurde aufgebraucht'

is_purchaseable: '&8[&e&l!&8] &c&lServer &8» &cDu kannst dir diesen Befehl mit /buy kaufen!'


usage:
  gift: '&8[&e&l!&8] &c&lVerwendung &8» &c /gift [Spieler]!'
  grant: '&8[&e&l!&8] &c&lVerwendung &8» &c /grant [Spieler]!'

item:
  name: '&8» &6%command%'
  lore:
    - '&7Stunden: &e%duration% Stunden'
    - '&7Preis: &c%price% Lumen'
    - '&7Server: &b%servers%'
    - '&7Cooldown: &e%cooldown% Stunden'
    - '%additional_lore%'           #Individual Lore per Item
  lore_uses: '&7Verwendungen &e%duration% '
  lore_days: '&7Tage: &e%duration%'

timeformat:
  days: ' Tag/e '
  hours: ' Stunde/n '
  minutes: ' Minute/n'

#############################################
##########     Bonus Commands    ############
#############################################

boatspawn: '&8[&e&l!&8] &c&lServer &8» &aBoot wurde erfolgreich gespawnt'

sleeping: '&8[&e&l!&8] &c&lServer &8» &aDu schläfst nun für 15 Sekunden'

sleeping_end: '&8[&e&l!&8] &c&lServer &8» &cDu schläfst nun nicht mehr'

sleep_only_at_night: '&8[&e&l!&8] &c&lServer &8» &cDu kannst nur Nachts schlafen'

launch: '&8[&e&l!&8] &c&lServer &8» &dWhoosh!'

launch_cd: '&8[&e&l!&8] &c&lServer &8» &cBitte warte einen Moment, bevor du den Befehl erneut benutzt'

average: '&8[&e&l!&8] &c&lServer &8» &7Der Preisdurchschnitt für &6%itemcount% %item% &7beträgt &e%avg% Lumen &7bei &e%count% &7Käufen gesamt'

no_item: '&8[&e&l!&8] &c&lServer &8» &cHalte ein Item in der Hand oder benutze optionale Argumente wie /avg <item> <anzahl> <Item Name> <Tage>'

hat_no_item: '&8[&e&l!&8] &c&lServer &8» &cBitte nimm ein Item in die Hand'

hat: '&8[&e&l!&8] &c&lServer &8» &aViel Spaß mit deinem Hut'

restart: '&8[&e&l!&8] &c&lServer &8» &aDu wurdest auf die Lobby wegen eines restarts teleportiert'

#############################################
##########    Random Teleport    ############
#############################################

rtp_sign:
  - ''
  - '&e&l[Klick]'
  - '&b&lZufallsTP'
  - ''

sign_created: '&8[&e&l!&8] &c&lServer &8» &aDu hast das ZufallsTp Schild erfolgreich erstellt'

teleported: '&8[&e&l!&8] &c&lServer &8» &aDu wurdest %distance% Blöcke weg teleportiert'

tp_cooldown: '&8[&e&l!&8] &c&lServer &8» &aDu kannst den Zufalls Teleport erst in %time% Sekunden wieder benutzen'

nodestination: '&8[&e&l!&8] &c&lServer &8» &cEs konnte kein sicherer Teleportplatz gefunden werden. Versuche es nochmal.'

#############################################
###########    Pipe Variables    ############
#############################################

pipe_info: '&8[&e&l!&8] &6&lPipe &8» &aEs werden folgende Items gefiltert: &e%items%'

no_region_member: '&8[&e&l!&8] &6&lPipe &8» &cDieses Schild gehört dir nicht'

no_valid_item: '&8[&e&l!&8] &6&lPipe &8» &cAuswahl ist kein Item'

no_pipe: '&8[&e&l!&8] &6&lPipe &8» &cDies ist kein [Pipe] Schild!'

no_sign: '&8[&e&l!&8] &6&lPipe &8» &cDies ist kein [Pipe] Schild!'

no_var_found: '&8[&e&l!&8] &6&lPipe &8» &cKeine Variable zu &e%item% &cgefunden!'

pipe_enabled: '&8[&e&l!&8] &6&lPipe &8» &aDeine plazierten Schilder werden nun automatisch zu [Pipe] Schilder'

pipe_disabled: '&8[&e&l!&8] &6&lPipe &8» &aDeine Schilder werden wieder normal plaziert!'

no_sign_space: '&8[&e&l!&8] &6&lPipe &8» &cDiese Variable passt nicht mehr aufs Schild!'

#############################################
############    Quest Rules    ##############
#############################################

quest_required: '&8[&e&l!&8] &6&lQuest &8» &cDu brauchst die Quest %questname% um das hier sammeln zu können!'

rule_added:
  - '&8[&e&l!&8] &6&lQuest &8» &aQuestregel hinzugefügt!'
  - '&aBlock: &e%block%'
  - '&aQuest Name: &e%quest%'
  - '&aTyp: &e%type%'
  - '&aRegenarationsZeit: &e%replant_time%'
  - '&aSound: &e%sound%'

rule_delete: '&8[&e&l!&8] &6&lQuest &8» &cRegel gelöscht!'

rule_exists: '&8[&e&l!&8] &6&lQuest &8» &cFür diesen Block gibt es bereits eine Regel!'

#############################################
############    Anti Afk    ##############
#############################################

afk_time: 15

afk_message: '&8[&e&l!&8] &6&lQuest &8» &cAFK Status erkannt. Teleportiere zum Spawn...!'

afk_location:
  world: world
  x: 82
  y: 89
  z: 151

#############################################
##############    Deaths    #################
#############################################

no_death: '&8[&e&l!&8] &6&lServer &8» &cKein Tod zu diesem Spieler gefunden'

deaths_usage: '&8[&e&l!&8] &6&lServer &8» &cVerwendung: /deaths <typ> <Spieler>'

#############################################
###########    Miscellaneous    #############
#############################################

flycheck: true

fly_expired: '&8[&e&l!&8] &6&lServer &8» &cDein Fly ist ausgelaufen!'

max_fly: 900

fly_decrease: 5

fly_increase: 1




